server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ {
    proxy_pass http://api:3000;
    proxy_http_version 1.1;
    proxy_buffering off;
  }
  location /health/ { proxy_pass http://api:3000; }
  location / { try_files $uri $uri/ /index.html; }
  location = /health/live { add_header Content-Type text/plain; return 200 'ok\n'; }
}
